In [95]:
import numpy as np
import pandas as pd

import plotly.graph_objects as go
from plotly.subplots import make_subplots

from sklearn.linear_model import LinearRegression, RidgeCV # CV auto finds optimal penalty to reduce coeffficients????
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# DAATA

In [66]:
df = pd.read_csv("./dataset2.csv")
print(df.head())

   feature1  feature2  feature3  observation
0 -1.594428 -1.606260  1.964725     1.661850
1 -0.599375 -0.619767  0.035264    -0.674192
2  0.005244  0.002550 -0.699726    -3.019403
3  0.046981  0.054156  0.213980    -1.103857
4 -0.450065 -0.435042 -0.112328    -0.668920


In [67]:
X = df.iloc[:, :3].to_numpy()
y = df.iloc[:, 3].to_numpy()

In [81]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Linear

In [82]:
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](3,)","[-21.88, 23.88, 2.92]"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,-0.9843
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,3
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int,3
"singular_ singular_: array of shape (min(X, y),)Singular values of `X`. Only available when `X` is dense.","ndarray[float64](3,)","[7.63,6.05,0.03]"


In [83]:
y_pred = linear_model.predict(X_test)

In [ ]:
a, b, c = linear_model.coef_
d = linear_model.intercept_
print(a, b, c, d)

-21.876353875944798 23.880703937199318 2.921456013053865 -0.9842595416861979


In [85]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

mse, r2

(1.5238815014983345, 0.7276098318244332)

# Ridge

In [ ]:
ridge_model = RidgeCV()
ridge_model.fit(X_train, y_train)

,"alphas alphas: array-like of shape (n_alphas,), default=(0.1, 1.0, 10.0)Array of alpha values to try.Regularization strength; must be a positive float. Regularizationimproves the conditioning of the problem and reduces the variance ofthe estimates. Larger values specify stronger regularization.Alpha corresponds to ``1 / (2C)`` in other linear models such as:class:`~sklearn.linear_model.LogisticRegression` or:class:`~sklearn.svm.LinearSVC`.If using Leave-One-Out cross-validation, alphas must be strictly positive.For an example on how regularization strength affects the model coefficients,see :ref:`sphx_glr_auto_examples_linear_model_plot_ridge_coeffs.py`.","(0.1, ...)"
,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto false, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"scoring scoring: str, callable, default=NoneThe scoring method to use for cross-validation. Options:- str: see :ref:`scoring_string_names` for options.- callable: a scorer callable object (e.g., function) with signature ``scorer(estimator, X, y)``. See :ref:`scoring_callable` for details.- `None`: negative :ref:`mean squared error <mean_squared_error>` if cv is None (i.e. when using leave-one-out cross-validation), or :ref:`coefficient of determination <r2_score>` (:math:`R^2`) otherwise.",None
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the efficient Leave-One-Out cross-validation- integer, to specify the number of folds,- :term:`CV splitter`,- an iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if ``y`` is binary or multiclass,:class:`~sklearn.model_selection.StratifiedKFold` is used, else,:class:`~sklearn.model_selection.KFold` is used.Refer :ref:`User Guide <cross_validation>` for the variouscross-validation strategies that can be used here.",None
,"gcv_mode gcv_mode: {'auto', 'svd', 'eigen'}, default='auto'Flag indicating which strategy to use when performingLeave-One-Out Cross-Validation. Options are:: 'auto' : same as 'eigen' 'svd' : use singular value decomposition of X when X is dense, fallback to 'eigen' when X is sparse 'eigen' : use eigendecomposition of X X' when n_samples <= n_features or X' X when n_features < n_samplesThe 'auto' mode is the default and is intended to pick the cheaperoption depending on the shape and sparsity of the training data.",None
,"store_cv_results store_cv_results: bool, default=FalseFlag indicating if the cross-validation values corresponding toeach alpha should be stored in the ``cv_results_`` attribute (seebelow). This flag is only compatible with ``cv=None`` (i.e. usingLeave-One-Out Cross-Validation)... versionchanged:: 1.5 Parameter name changed from `store_cv_values` to `store_cv_results`.",False
,"alpha_per_target alpha_per_target: bool, default=FalseFlag indicating whether to optimize the alpha value (picked from the`alphas` parameter list) for each target separately (for multi-outputsettings: multiple prediction targets). When set to `True`, afterfitting, the `alpha_` attribute will contain a value for each target.When set to `False`, a single alpha is used for all targets.This flag is only compatible with ``cv=None`` (i.e. usingLeave-One-Out Cross-Validation)... versionadded:: 0.24",False
Name,Type,Value
"alpha_ alpha_: float or ndarray of shape (n_targets,)Estimated regularization parameter, or, if ``alpha_per_target=True``,the estimated regularization parameter for each target.",float,0.1
"best_score_ best_score_: float or ndarray of shape (n_targets,)Score of base estimator with best alpha, or, if``alpha_per_target=True``, a score for each target... versionadded:: 0.23",float64,-0.8184
"coef_ coef_: ndarray of shape (n_features) or (n_targets, n_features)Weight vector(s).","ndarray[float64](3,)","[0.84,1.21,2.9 ]"


In [87]:
y_pred_ridge = ridge_model.predict(X_test)

In [88]:
a_ridge, b_ridge, c_ridge = ridge_model.coef_
d_ridge = ridge_model.intercept_
print(a_ridge, b_ridge, c_ridge, d_ridge)

0.836870086746821 1.2104784752779427 2.8970293621489027 -1.0907534095206257


In [89]:
mse_ridge = mean_squared_error(y_test, y_pred_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

mse_ridge, r2_ridge

(1.4021049228983646, 0.7493771035526327)

# HMMM

In [90]:
x_min, x_max = X_train[:, 0].min(), X_train[:, 0].max()
y_min, y_max = X_train[:, 1].min(), X_train[:, 1].max()
z_min, z_max = X_train[:, 2].min(), X_train[:, 2].max()

x_vals, y_vals, z_vals = np.mgrid[x_min:x_max:30j, y_min:y_max:30j, z_min:z_max:30j]

In [ ]:
fig = make_subplots(
    rows=2,
    cols=2,
    specs=[
        [{"type": "scatter3d"}, {"type": "scatter3d"}],
        [{"type": "scatter3d"}, {"type": "scatter3d"}],
    ],
)

linear_values = a * x_vals + b * y_vals + c * z_vals + d
ridge_values = a_ridge * x_vals + b_ridge * y_vals + c_ridge * z_vals + d_ridge

datas = [[X_train, y_train, linear_values], [X_test, y_test, linear_values],
        [X_train, y_train, ridge_values], [X_test, y_test, ridge_values]]


for i, data in enumerate(datas):
    [X_data, y_data, values_data] = data

    row = i // 2 + 1
    col = i % 2 + 1

    fig.add_trace(
        go.Volume(
            x=x_vals.flatten(),
            y=y_vals.flatten(),
            z=z_vals.flatten(),
            value=values_data.flatten(),
            isomin=values_data.min(),
            isomax=values_data.max(),
            opacity=0.7,
            surface_count=20,
            colorscale="Inferno",
            showscale=True if i == 0 else False,
            showlegend=False,
        ),
        row=row,
        col=col,
    )

    fig.add_trace(
        go.Scatter3d(
            x=X_data[:, 0],
            y=X_data[:, 1],
            z=X_data[:, 2],
            mode="markers",
            marker=dict(
                size=6,
                color=y_data,
                colorscale="Inferno",
                opacity=0.8,
                showscale=False,
            ),
            showlegend=False
        ),
        row=row,
        col=col
    )

fig.update_layout(
    scene=dict(
        xaxis_title="1", yaxis_title="2", zaxis_title="3"
    ),
    scene2=dict(
        xaxis_title="1", yaxis_title="2", zaxis_title="3"
    ),
    scene3=dict(
        xaxis_title="1", yaxis_title="2", zaxis_title="3"
    ),
    scene4=dict(
        xaxis_title="1", yaxis_title="2", zaxis_title="3"
    ),
    font=dict(size=10),
)

fig.show()

# Iterations

In [112]:
N = 15

In [155]:
coefficients_linear_iterations = np.zeros((0, 5))
coefficients_ridge_iterations = np.zeros((0, 5))


for _ in range(N):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

    linear_model = LinearRegression()
    linear_model.fit(X_train, y_train)
    y_pred_linear = linear_model.predict(X_test)
    r2_linear = r2_score(y_test, y_pred_linear)
    coefficients_linear_iterations = np.vstack((coefficients_linear_iterations, [*linear_model.coef_, linear_model.intercept_, r2_linear]))

    ridge_model = RidgeCV()
    ridge_model.fit(X_train, y_train)
    y_pred_ridge = ridge_model.predict(X_test)
    r2_ridge = r2_score(y_test, y_pred_ridge)
    coefficients_ridge_iterations = np.vstack((coefficients_ridge_iterations, [*ridge_model.coef_, ridge_model.intercept_, r2_ridge]))

print(coefficients_linear_iterations)
print(coefficients_ridge_iterations)

[[-33.37666523  35.32028262   3.1116711   -1.05808039   0.89766639]
 [-42.67744595  44.46739812   2.92610857  -0.95851205   0.91236024]
 [-28.47397038  30.33713638   2.92347856  -1.0316883    0.93381581]
 [-15.6529886   17.53919329   2.96655271  -0.9868225    0.95660373]
 [ -9.80604101  11.68027535   3.17228302  -1.16538819   0.89969768]
 [-23.03301181  24.69869469   2.96776328  -0.8797343    0.95386699]
 [ 15.19519799 -13.28493767   2.8997672   -1.01907322   0.92028963]
 [-21.07384615  22.92955923   2.9364524   -0.91403769   0.88598917]
 [-11.89030294  13.8966452    2.86930337  -1.07571879   0.95839199]
 [-41.22673499  42.80301269   3.09696722  -0.90266848   0.33662941]
 [ -9.47527869  11.41216975   2.8904003   -0.98113375   0.95756817]
 [  7.15221822  -5.36368957   2.80710353  -0.95175001   0.94514981]
 [ -2.7991018    4.62055828   2.8587735   -0.93807901   0.90817379]
 [-17.17476422  19.27011496   3.07711215  -1.18834357   0.91959055]
 [-17.06573159  18.97816968   2.84690731  -0.888