There is non linearity due to sin term

we could have high dim even with one by time delat multiplexing

damping so fading memory

In [6]:
import numpy as np

In [7]:
rng_val = 42

steps = 20000
dt = 0.01
m = 1.0
l = 1.0
g = 9.81

# Cart x and v
# Pendulum theta and omega
matrix_size = 4

In [14]:
def run_single_pendulum(
    steps,
    dt,
    m,
    l,
    g,
    cart_forces
):
    x = np.zeros(matrix_size)
    v = np.zeros(matrix_size)
    theta = np.zeros(matrix_size)
    omega = np.zeros(matrix_size)
    for i in range(1, steps):
        alpha = (g * np.sin(theta[i-1]) - cart_forces[i-1] * np.cos(theta[i-1])) / l
        print(omega[:5])
        print(alpha)

        omega[i] = omega[i-1] + alpha * dt
        theta[i] = theta[i-1] + omega[i] * dt
        theta[i] = ((theta[i] + np.pi) % (2 * np.pi)) - np.pi

        v[i] = v[i-1] + cart_forces[i-1] * dt
        x[i] = x[i-1] + v[i] * dt

    return x, v, theta, omega

In [15]:
(g * np.sin(0) - 0 * np.cos(0)) / l

np.float64(0.0)

In [16]:
cart_forces = np.zeros(steps)

x, v, theta, omega = run_single_pendulum(
    steps,
    dt,
    m,
    l,
    g,
    cart_forces
)

[0. 0. 0. 0.]
0.0
[0. 0. 0. 0.]
0.0
[0. 0. 0. 0.]
0.0
[0. 0. 0. 0.]
0.0


IndexError: index 4 is out of bounds for axis 0 with size 4